# Default values for spring-music.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: myharbor.com/library/spring-music
  tag: '1.0'
  pullPolicy: IfNotPresent
