---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: staging
  name: spring-music
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
  labels:
    appName: spring-music
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: spring-music
  template:
    metadata:
      labels:
        appName: spring-music
    spec:
      containers:
        - name: spring-music
          image: "harbor.infra.aws.warroyo.com/library/spring-music:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            null