# Default values for spring-music.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: harbor.infra.aws.warroyo.com/library/spring-music
  tag: '1.0'
  pullPolicy: IfNotPresent
service:
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: false