# Default values for spring-music.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.infra.aws.warroyo.com/library/spring-music
  tag: '1.0'
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

ingress:
  enabled: true
  hosts: 
    - spring-music-test1.spinnaker.gcp.warroyo.com
  annotations:
    kubernetes.io/ingress.class: nginx
